### ISSUE TITLE
Access to latitudeDegrees and longitudeDegrees from library

### ISSUE THREAD

**Issue by kenwalker** [spark/AssetTracker#13]
I'm working on a project where I'd like access to _latitudeDegrees_ and _longitudeDegrees_ but at the moment the only access is through _readLatLon()_ and you'd have to parse the string results.

Adding accessors in AssetTracker.cpp and AssetTracker.h is pretty trivial and I'll open up a pull request.

**Comment by jenesaisdiq** [comment]
Nice!
