### ISSUE TITLE
uBlox branch returning junk GPS data

### ISSUE THREAD

**Issue by jenesaisdiq** [spark/AssetTracker#23]
Hey @mohitbhoite, I'm using the first example to publish out the GPS location and I'm getting garbage. Function returns 1, which should indicate it has a fix, but I'm getting data like 
`97.000000,0.000000`

Also haven't seen the SAT_FIX LED blinking, so maybe that needs to be ported to this hardware as well?

**Comment by mohitbhoite** [comment]
This should be resolved with the latest commit.
The internal antenna is selected by default now and the GPS fix routine checks for both the LAT and LONG locks.
